# Created 2019-01-13 Sun 16:21
#+TITLE: go through fifth chapter
#+AUTHOR: Andrea Giugliano
Into the depth of dependent types now. So far we had an object with a
given type and some properties we wanted to prove true.

Some of the properties we really care about are called invariant:
these need to hold on any instance of the object.

Let's consider the list and length definitions that we have already encountered:

#+begin_src agda2
data ğ•ƒ {â„“} (A : Set â„“) : Set â„“ where
  [] : ğ•ƒ A
  _::_ : (x : A) (xs : ğ•ƒ A) â†’ ğ•ƒ A

length : âˆ€{â„“}{A : Set â„“} â†’ ğ•ƒ A â†’ â„•
length [] = 0
length (x :: xs) = suc (length xs)
#+end_src

An invariant that we expect on the list is that adding elements
affects the length of the list. For ascertain the invariant we would
need proofs.

What about embedding the invariant (and its proof) in the type itself?

Let's look at a dependent typed version of list: vector

#+begin_src agda2
data ğ• {â„“} (A : Set â„“) : â„• â†’ Set â„“ where
  [] : ğ• A 0
  _::_ : {n : â„•} â†’ A â†’ ğ• A n â†’ ğ• A (suc n)
#+end_src

In the type we expressly state that we will have a vector type only if
we give a natural. This natural represents the length of the vector,
and the datatype cases define its value.

This let us skip all proofs for length: for example the append
operation now does not need any proof on length, as it enforces it in
the type:

#+begin_src agda2
_++ğ•_ : âˆ€ {â„“} {A : Set â„“}{n m : â„•} â†’ ğ• A n â†’ ğ• A m â†’ ğ• A (n + m) -- here our proof!
[]        ++ğ• ys = ys
(x :: xs) ++ğ• ys = x :: xs ++ğ• ys
#+end_src

But not only that, we can even avoid invalid definitions. For example
defining ~head~ for a list is painful, as we have to handle the empty
list case for which there is no head. In a dependent type setting
there is no need of handling side effects (no exception, no monad): we
define ~head~ only for vectors with a length greater than zero.

#+begin_src agda2
headğ• : âˆ€ {â„“} {A : Set â„“}{n : â„•} â†’ ğ• A (suc n) â†’ A -- (suc n) does the magic here!
headğ• (x :: _) = x
#+end_src

Similarly we can leave undefined the ~nth~ operation for indexes that
are greater than the length of the list:

#+begin_src agda2
nthğ• : âˆ€ {â„“} {A : Set â„“}{m : â„•} â†’ (n : â„•) â†’ n < m â‰¡ tt â†’ ğ• A m â†’ A
nthğ• 0 _ (x :: _) = x
nthğ• (suc n) p (_ :: xs) = nthğ• n p xs
nthğ• (suc n) () []
nthğ• 0 () []
#+end_src

This definition introduces us to the difference between external and
internal verification: all the proofs of external verified software
can live separated from the definitions they refer to; the proofs of
internal verified software need to embedded in the definition.

Given the type ~nthğ• : âˆ€ {â„“} {A : Set â„“}{m : â„•} â†’ (n : â„•) â†’ n < m â‰¡ tt
â†’ ğ• A m â†’ A~, we have as (explicit) parameters:

- the index ~(n : â„•)~
- a proof that the given index is smaller than the vector length ~n < m â‰¡ tt~
- the vector to search ~ğ• A m~

The proof is the reason why the last two cases we use the impossible
pattern to *define* the operation: we say that ~nth~ is undefined for
any index in case of an empty vector, as the proof cannot hold.

(Funny thing is that one can use holes to analyze cases. If one also
uses the solver for proofs, the implementation of ~nth~ could be
unexpected).


We can do the same for datatypes with "more intense" invariant. Say we
want to model a binary search tree. The invariant here has to do with
the order of the elements: in such a tree values are added according
to an order, so that one can skip accessing unneeded set of values
during retrieval.

Let's start from the imports that we will need for this data
structure:

#+begin_src agda2
open import bool
open import bool-thms2
open import eq
open import maybe
open import product
open import product-thms
open import bool-relations using (transitive ; total)
#+end_src

All of the imports provide pieces we will need for the definition of
the type. Note that we will need theorems. An interesting import is the
one for the order: ~open import bool-relations using (transitive ;
total)~. We will use a total order defined in a boolean fashion:

#+begin_src agda2
{- This file describes properties of computable relations. -}

open import bool
open import level
open import eq
open import product
open import product-thms

module bool-relations {â„“ : level}{A : Set â„“} (_â‰¤A_ : A â†’ A â†’ ğ”¹) where

reflexive : Set â„“
reflexive = âˆ€ {a : A} â†’ a â‰¤A a â‰¡ tt

transitive : Set â„“
transitive = âˆ€ {a b c : A} â†’ a â‰¤A b â‰¡ tt â†’ b â‰¤A c â‰¡ tt â†’ a â‰¤A c â‰¡ tt

total : Set â„“
total = âˆ€ {a b : A} â†’ a â‰¤A b â‰¡ ff â†’ b â‰¤A a â‰¡ tt

total-reflexive : total â†’ reflexive 
total-reflexive tot {a} with keep (a â‰¤A a)
total-reflexive tot {a} | tt , p = p
total-reflexive tot {a} | ff , p = tot p

_isoğ”¹_ : A â†’ A â†’ ğ”¹
d isoğ”¹ d' = d â‰¤A d' && d' â‰¤A d

isoğ”¹-intro : âˆ€{x y : A} â†’ x â‰¤A y â‰¡ tt â†’ y â‰¤A x â‰¡ tt â†’ x isoğ”¹ y â‰¡ tt
isoğ”¹-intro p1 p2 rewrite p1 | p2 = refl
#+end_src

The core part of the above module is the relation: ~_â‰¤A_~. This
represents the order. The rest of the definitions are properties the
order respects. The isomorphism stands roughly for equality.

Equipped of these definitions and theorems we can finally look at the
binary search tree definition:

#+begin_src agda2
module bst (A : Set) (_â‰¤A_ : A â†’ A â†’ ğ”¹)
           (â‰¤A-trans : transitive _â‰¤A_)
           (â‰¤A-total : total _â‰¤A_) where

open import bool-relations _â‰¤A_ hiding (transitive ; total)
open import minmax _â‰¤A_ â‰¤A-trans â‰¤A-total

data bst : A â†’ A â†’ Set where
  bst-leaf : âˆ€ {l u : A} â†’ l â‰¤A u â‰¡ tt â†’ bst l u
  bst-node : âˆ€ {l l' u' u : A}(d : A) â†’ 
               bst l' d â†’ bst d u' â†’ 
               l â‰¤A l' â‰¡ tt â†’ u' â‰¤A u â‰¡ tt â†’ 
               bst l u
#+end_src

We use the boolean order relation to order values of type A. The leaf
is empty and its only invariant is that ~l~ and ~u~ (lowe and upper
bound respectively) are in order. The node contains a value of type A
~(d : A)~ and two trees ~bst l' d â†’ bst d u'~. The invariant for the
node is that its lower and upper bounds work as lower and upper bounds
also for the subtrees ~l â‰¤A l' â‰¡ tt â†’ u' â‰¤A u â‰¡ tt~.

Given this let's look at an operation on trees: insert. This is where
things become quite complicated:

#+begin_src agda2
bst-insert : âˆ€{l u : A}(d : A) â†’ bst l u â†’ bst (min d l) (max d u)
bst-insert d (bst-leaf p) = bst-node d (bst-leaf â‰¤A-refl) (bst-leaf â‰¤A-refl) min-â‰¤1 max-â‰¤1
bst-insert d (bst-node d' L R p1 p2) with keep (d â‰¤A d') 
bst-insert d (bst-node d' L R p1 p2) | tt , p with bst-insert d L
bst-insert d (bst-node d' L R p1 p2) | tt , p | L' rewrite p = 
  bst-node d' L' (bst-inc-ub R (â‰¤A-trans p2 max-â‰¤2)) (min2-mono p1) â‰¤A-refl
bst-insert d (bst-node d' L R p1 p2) | ff , p with bst-insert d R
bst-insert d (bst-node d' L R p1 p2) | ff , p | R' rewrite p = 
  bst-node d' (bst-dec-lb L p1) R' min-â‰¤2 (max2-mono p2)
#+end_src

We use ~min~ and ~max~ to keep the type flexible: we want to add an
element, but we do not know if the element is going to become the new
lower or upper bound. This design decision affects our definition as
the proofs now need to involve the ~min~ and ~max~ definitions (as
well as some lemmas on them).

Let's take a few of the cases: the simplest one is when we insert in a
leaf tree. This is our first insertion, that will make the leaf a node
with the given value. In ~bst-insert d (bst-leaf p) = bst-node d
(bst-leaf â‰¤A-refl) (bst-leaf â‰¤A-refl) min-â‰¤1 max-â‰¤1~ we prove that the
node contains the value and two leaves and we prove that the order
between keys is preserved through ~min~ and ~max~ theorems.

For the node insertion we do case analysis and we end doing proper
theorem proving to define an implementation.



Dependent typed languages need to provide abstractions to make types
depend on other types. This is what Î£ and âŠ are for.

#+begin_src agda2
data Î£ {â„“ â„“'} (A : Set â„“) (B : A â†’ Set â„“') : Set (â„“ âŠ” â„“') where
  _,_ : (a : A) â†’ (b : B a) â†’ Î£ A B

data _âŠ_ {â„“ â„“'} (A : Set â„“) (B : Set â„“') : Set (â„“ âŠ” â„“') where
  injâ‚ : (x : A) â†’ A âŠ B
  injâ‚‚ : (y : B) â†’ A âŠ B
#+end_src

Î£ generalizes products (really pairs). The second element of a pair
exists in function of the first element: ~(b : B a)~ means that ~b~
can use ~a~ for its definition (e.g., say ~A~ is a vector, ~B~ may
depend of the vector length).

âŠ generalizes sums. It is isomorphic to the logical or really.

Some exercises:

#+begin_src agda2
-- 5.1
_by_matrix : â„• â†’ â„• â†’ Set
n by m matrix = ğ• (ğ• â„• n) m

-- TO CONTINUE
#+end_src
