# Created 2018-11-14 Wed 00:50
#+TITLE: go through second chapter
#+AUTHOR: Andrea Giugliano
Let's discover the shining dark of Agda: theorem proving!

First let's define a theorem to prove:

#+BEGIN_SRC agda2
module bool-test where

open import bool
open import eq
open import level

~~tt : ~ ~ tt â‰¡ tt
~~tt = refl
#+END_SRC

We state that a double negation of true produce true. The interesting
bit here is how similar is a theorem to a definition. Take for
example, the definition of negation:

#+BEGIN_SRC agda2
-- not
~_ : ğ”¹ â†’ ğ”¹
~ tt = ff
~ ff = tt
#+END_SRC

In both we have a type definition (=~~tt : ~ ~ tt â‰¡ tt= and =~_ : ğ”¹ â†’
ğ”¹= respectively), and a definition part (=~~tt = refl= and =~ tt = ff
~ ff = tt= respectively).

So basically proof and code can be treated transparently. All of
this is possible thanks to the The "Curry-Howard Isomorphism":
basically there is a bidirectional transformation between logic,
algebra, and types.

So what is the type of =â‰¡=? It's type is ={â„“ : Level} {A : Set â„“} â†’ A
â†’ A â†’ Set â„“=. So given two elements of a set of a certain level, it
returns a set of the same level. So basically, the theorem itself is a
type.

Another important part of the above theorem is the use of =refl=. This
stands for reflexivity: given two same objects, they are equivalent
for reflexivity. 

What is =refl= type? It's type is =_x_4 â‰¡ _x_4=. So reflexivity
produces a proof type: this is just too cool!

By the way, this means that =refl= has implicit type parameters that
we can instantiate: 

#+BEGIN_SRC agda2
~~tt : ~ ~ tt â‰¡ tt
~~tt = refl{lzero}{ğ”¹}{tt} -- refl type is {â„“ : Level} {A : Set â„“} â†’ A â†’ A â†’ Set â„“
                          -- so the associations are 
                          --   lzero -> â„“, 
                          --   ğ”¹ -> Set â„“, 
                          --   tt -> A
#+END_SRC

Let's generalize our result then: universal quantification!

#+BEGIN_SRC agda
module bool-thms where

open import bool
open import eq
open import sum

~~-elim : âˆ€ (b : ğ”¹) â†’ ~ ~ b â‰¡ b
~~-elim tt = refl
~~-elim ff = refl
#+END_SRC

Again Agda's pattern matching looks elegant for a universal quantified
variable.

- type refinement :: Agda resolves the theorem starting from the
  instantiation of the pattern matching: once we give =~~-elim tt=
  as a pattern match, Agda substitutes =b= with =tt= in the
  formula: so =~ ~ b â‰¡ b= becomes =~ ~ tt â‰¡ tt=. Now, Agda
  substitutes with the =~= definition and gets =~ ff â‰¡ tt=, then
  ==tt â‰¡ tt==. At this point =refl= is the solution!

Let's compare the universal quantifier uses:

1. as universal quantifier on the type set =~~-elim : âˆ€ (b : ğ”¹) â†’ ~ ~
      b â‰¡ b=
2. as a way to express polymorphism =if_then_else_ : âˆ€ {â„“} {A : Set â„“}
      â†’ ğ”¹ â†’ A â†’ A â†’ A=

In both cases it quantifies over a type.

Agda fills in question marks with holes (does it do it also for normal
definitions, or only for proofs?). For example the theorem definition

#+BEGIN_SRC agda2
~~-elim : âˆ€ (b : ğ”¹) â†’ ~ ~ b â‰¡ b
~~-elim = ?
#+END_SRC

after pressing =CcCl= becomes

#+BEGIN_SRC agda2
~~-elim : âˆ€ (b : ğ”¹) â†’ ~ ~ b â‰¡ b
~~-elim = { }0
#+END_SRC

With the goal buffer showing:

#+BEGIN_SRC agda2
?0 : (b : ğ”¹) â†’ ~ (~ b) â‰¡ b
#+END_SRC

Holes seem goals. They are modifiable in place. Given enough context,
Agda can also find the hole solution for us.


Apparently implicit parameters can be useful in compacting the syntax.
For example we can universally quantify on a type (note that Agda can
infer the type of the following through the type of =&&=):
#+BEGIN_SRC agda2
&&-idem : âˆ€ {b} â†’ b && b â‰¡ b
&&-idem{tt} = refl
&&-idem{ff} = refl
#+END_SRC

Now if we want to use this theorem in another proof we can avoid to
explicitly state the values =tt= and =ff=.

And more: hypothesis! The idea is that other theorems can work as
hypothesis through implication:

#+BEGIN_SRC agda2
||â‰¡ffâ‚ : âˆ€ {b1 b2} â†’ b1 || b2 â‰¡ ff â†’ ff â‰¡ b1
||â‰¡ffâ‚ {ff} p = refl
||â‰¡ffâ‚ {tt} ()
#+END_SRC

So given the hypothesis =b1 || b2 â‰¡ ff= we expect =b1= to be false.
We see that instantiating =b1= to =ff= and =b2= to a variable value
=p=, we can prove the case by reflexivity. When =b1= is equal to =tt=
instead, we can use =()=, which is a rule that stands for absurd.

The absurd pattern is used to quit early in the proof when we
recognize an impossible hypothesis: in this case if =b1= is =tt=, then
we are gonna have =tt || b2 â‰¡ ff=, that is =tt â‰¡ ff=, which is
impossible.


#+BEGIN_SRC agda2
||â‰¡ffâ‚ : âˆ€ {b1 b2} â†’ b1 || b2 â‰¡ ff â†’ ff â‰¡ b1
||â‰¡ffâ‚ {ff} p = refl
||â‰¡ffâ‚ {tt} p = sym p
#+END_SRC
The rule =sym= stands for symmetry. Its type is ={â„“ :
.Agda.Primitive.Level} {A : Set â„“} {x y : A} â†’ x â‰¡ y â†’ y â‰¡ x=:
basically given a value, it flips the order of the equation.

Another interesting proof is the following:
#+BEGIN_SRC agda2
||-congâ‚ : âˆ€ {b1 b1' b2} â†’ b1 â‰¡ b1' â†’ b1 || b2 â‰¡ b1' || b2
||-congâ‚ refl = refl
#+END_SRC

Here we use =refl= on both sides of the pattern. This works only
because the =b1= can be substituted by =b1'=, and the formulas become
equivalent.

Finally, we have another rule to take in account:
#+BEGIN_SRC agda2
||-congâ‚‚ : âˆ€ {b1 b2 b2'} â†’ b2 â‰¡ b2' â†’ b1 || b2 â‰¡ b1 || b2'
||-congâ‚‚ p rewrite p = refl
#+END_SRC

=rewrite= just simplifies terms: in this case the =b2= on the left
hand side of the theorem would be solved by reflexivity if it were a
=b2'=...

The Curry-Horward targeted constructive logic which is a subset of
classical logic. The principle is that we want to know exactly what
makes us sure that a fact is valid: for example, if the predicate
=a || b= returns =tt=, in constructive logic we must know which of the
terms produced =tt=; while in classic logic we can be uncertain.

Certain proofs are non constructive. Id est, these proofs rely on the
excluded middle theorem: a predicate can only be true or false. Agda
does not support these proofs.

And universal quantification on types:
#+BEGIN_SRC agda2
ite-same : âˆ€{â„“}{A : Set â„“} â†’ 
           âˆ€(b : ğ”¹) (x : A) â†’ 
           (if b then x else x) â‰¡ x
ite-same tt x = refl
ite-same ff x = refl
#+END_SRC

This just says that an =if_then_else_= with the same return for both
clauses is equivalent to the return itself. This theorem can be
abstracted over any type.


My solution to the exercises:

#+BEGIN_SRC agda2
||â‰¡ff : âˆ€ {b1 b2} â†’ b1 || b2 â‰¡ ff â†’ ff â‰¡ b1
||â‰¡ff {tt} p  = sym p -- ag: the idea is just reverse the formula "tt || b2 â‰¡ ff" as this becomes  ff â‰¡ tt || b2 â†’ ff â‰¡ tt
||â‰¡ff {ff} p  = refl

excluded-middle : âˆ€{b} â†’ b || ~ b â‰¡ tt
excluded-middle{tt} = refl
excluded-middle{ff} = refl

a : tt â‰¡ tt
a = refl
b : ff â‰¡ ff
b = refl
-- ff â‰¡ tt nope
d : ff && ff â‰¡ ~ tt
d = refl
e : âˆ€ (x : ğ”¹) â†’ tt && x â‰¡ x
e x = refl
f : âˆ€ (x : ğ”¹) â†’ x && tt â‰¡ x
f tt = refl
f ff = refl
#+END_SRC
